const express = require('express');
const bodyParser = require('body-parser');
const { scrapeComics, scrapeComicsChapter, scrapeSoundtrack, scrapeSoundtrackForShow, scrapeKenmei } = require('./scrapes');
const request = require('request');

const app = express();
const port = process.env.PORT || 5000;

const listURL = [
  'https://manhwatop.net/manhwa/bart-simpson',
  'https://manhwatop.net/manhwa/fever-dreams',
  'https://manhwatop.net/manhwa/the-case-of-charles-dexter-ward',
  'https://manhwatop.net/manhwa/the-graphic-canon',
  'https://manhwatop.net/manhwa/all-waldo-comics',
  'https://manhwatop.net/manhwa/marilyns-monsters',
  'https://manhwatop.net/manhwa/erospsyche',
  'https://manhwatop.net/manhwa/the-illegitimates',
  'https://manhwatop.net/manhwa/monkey-jank',
  'https://manhwatop.net/manhwa/the-straw-king',
  'https://manhwatop.net/manhwa/the-world-of-thorgal-wolfcub',
  'https://manhwatop.net/manhwa/dryad',
  'https://manhwatop.net/manhwa/nomen-omen',
  'https://manhwatop.net/manhwa/miskatonic',
  'https://manhwatop.net/manhwa/2000-ad',
  'https://manhwatop.net/manhwa/the-lions-of-leningrad',
  'https://manhwatop.net/manhwa/kriss-of-valnor-red-as-the-raheborg',
  'https://manhwatop.net/manhwa/the-lost-ages',
  'https://manhwatop.net/manhwa/omni-visibilis',
  'https://manhwatop.net/manhwa/forget-me-not',
  'https://manhwatop.net/manhwa/elles',
  'https://manhwatop.net/manhwa/elecboy',
  'https://manhwatop.net/manhwa/cable-2020',
  'https://manhwatop.net/manhwa/excalibur-2019',
  'https://manhwatop.net/manhwa/bitter-root',
  'https://manhwatop.net/manhwa/red-warrior-assassin-for-the-thieves-world',
  'https://manhwatop.net/manhwa/ultramega-by-james-harren',
  'https://manhwatop.net/manhwa/southern-dog',
  'https://manhwatop.net/manhwa/east-coast-rising',
  'https://manhwatop.net/manhwa/up-from-the-deep',
  'https://manhwatop.net/manhwa/whispers-in-the-walls',
  'https://manhwatop.net/manhwa/journey-by-starlight',
  'https://manhwatop.net/manhwa/outlander',
  'https://manhwatop.net/manhwa/count',
  'https://manhwatop.net/manhwa/gobbledygook',
  'https://manhwatop.net/manhwa/wet-dreams',
  'https://manhwatop.net/manhwa/nash',
  'https://manhwatop.net/manhwa/mirage-mini-comics',
  'https://manhwatop.net/manhwa/house-of-women',
  'https://manhwatop.net/manhwa/bilals-monster',
  'https://manhwatop.net/manhwa/jim-hensons-the-storyteller-tricksters',
  'https://manhwatop.net/manhwa/bequest',
  'https://manhwatop.net/manhwa/illegal',
  'https://manhwatop.net/manhwa/the-supernaturalist',
  'https://manhwatop.net/manhwa/code-name-scorpio',
  'https://manhwatop.net/manhwa/bags-or-a-story-thereof',
  'https://manhwatop.net/manhwa/hoodoo',
  'https://manhwatop.net/manhwa/samaris',
  'https://manhwatop.net/manhwa/rush-limbaugh-must-die',
  'https://manhwatop.net/manhwa/the-trials-of-ultraman',
  'https://manhwatop.net/manhwa/captain-america-anniversary-tribute',
  'https://manhwatop.net/manhwa/black-knight-curse-of-the-ebony-blade',
  'https://manhwatop.net/manhwa/deadbeats',
  'https://manhwatop.net/manhwa/the-king-in-yellow',
  'https://manhwatop.net/manhwa/the-book-of-god-how-we-got-the-bible',
  'https://manhwatop.net/manhwa/heart-of-darkness',
  'https://manhwatop.net/manhwa/the-man-who-laughs',
  'https://manhwatop.net/manhwa/white-like-she',
  'https://manhwatop.net/manhwa/billie-the-bee',
  'https://manhwatop.net/manhwa/groo-25th-anniversary-special',
  'https://manhwatop.net/manhwa/sergio-aragones-groo-the-most-intelligent-man-in-the-world',
  'https://manhwatop.net/manhwa/american-splendor-the-life-and-times-of-harvey-pekar',
  'https://manhwatop.net/manhwa/tigress-tales',
  'https://manhwatop.net/manhwa/great-northern-brotherhood-of-canadian-cartoonists',
  'https://manhwatop.net/manhwa/reds-planet',
  'https://manhwatop.net/manhwa/cyberswine',
  'https://manhwatop.net/manhwa/rangeland-love',
  'https://manhwatop.net/manhwa/romance-diary',
  'https://manhwatop.net/manhwa/cato-and-the-zulus',
  'https://manhwatop.net/manhwa/map-of-my-heart',
  'https://manhwatop.net/manhwa/girl-in-dior',
  'https://manhwatop.net/manhwa/action-figure-the-adventures-of-doonesburys-uncle-duke',
  'https://manhwatop.net/manhwa/pigeons-from-hell-1991',
  'https://manhwatop.net/manhwa/ironhand-of-almuric',
  'https://manhwatop.net/manhwa/riftwar',
  'https://manhwatop.net/manhwa/romance-tales',
  'https://manhwatop.net/manhwa/rice-boy',
  'https://manhwatop.net/manhwa/virgins-wood',
  'https://manhwatop.net/manhwa/blade-runner-origins',
  'https://manhwatop.net/manhwa/the-doonesbury-chronicles',
  'https://manhwatop.net/manhwa/zippy-stories',
  'https://manhwatop.net/manhwa/are-we-having-fun-yet',
  'https://manhwatop.net/manhwa/worms-of-the-earth',
  'https://manhwatop.net/manhwa/extinction-seed',
  'https://manhwatop.net/manhwa/luann-stress-hormones-high-school',
  'https://manhwatop.net/manhwa/berkeley-breatheds-outland-the-complete-digital-collection',
  'https://manhwatop.net/manhwa/bolero',
  'https://manhwatop.net/manhwa/how-to-be-happy',
  'https://manhwatop.net/manhwa/strange-suspense-stories-1952',
  'https://manhwatop.net/manhwa/making-friends',
  'https://manhwatop.net/manhwa/daym-drops',
  'https://manhwatop.net/manhwa/lurkers',
  'https://manhwatop.net/manhwa/cavewoman-starship-blish',
  'https://manhwatop.net/manhwa/lorna-mouse-club',
  'https://manhwatop.net/manhwa/happiness-will-follow',
  'https://manhwatop.net/manhwa/superman-red-blue',
  'https://manhwatop.net/manhwa/revolver-2021',
  'https://manhwatop.net/manhwa/ancestor',
  'https://manhwatop.net/manhwa/lorna-leviathan',
  'https://manhwatop.net/manhwa/karney',
  'https://manhwatop.net/manhwa/hidden-face',
  'https://manhwatop.net/manhwa/the-jungle',
  'https://manhwatop.net/manhwa/the-book-of-five-rings',
  'https://manhwatop.net/manhwa/the-stranger-the-graphic-novel',
  'https://manhwatop.net/manhwa/tragg-and-the-sky-gods',
  'https://manhwatop.net/manhwa/spinning',
  'https://manhwatop.net/manhwa/new-world-order',
  'https://manhwatop.net/manhwa/brad-barron',
  'https://manhwatop.net/manhwa/garlandia',
  'https://manhwatop.net/manhwa/hard-looks',
  'https://manhwatop.net/manhwa/falka',
  'https://manhwatop.net/manhwa/necronomicon',
  'https://manhwatop.net/manhwa/love-is-just-another-kind-of-hate',
  'https://manhwatop.net/manhwa/the-love-bunglers',
  'https://manhwatop.net/manhwa/the-secret-of-kells',
  'https://manhwatop.net/manhwa/melowy',
  'https://manhwatop.net/manhwa/actual-confessions',
  'https://manhwatop.net/manhwa/love-adventures',
  'https://manhwatop.net/manhwa/to-my-eyes',
  'https://manhwatop.net/manhwa/bagdad-inc',
  'https://manhwatop.net/manhwa/hup',
  'https://manhwatop.net/manhwa/mother-come-home',
  'https://manhwatop.net/manhwa/tiananmen-1989-our-shattered-hopes',
  'https://manhwatop.net/manhwa/the-calling-cthulhu-chronicles',
  'https://manhwatop.net/manhwa/image-holiday-special-2005',
  'https://manhwatop.net/manhwa/education',
  'https://manhwatop.net/manhwa/little-aspirin',
  'https://manhwatop.net/manhwa/little-lizzie-1949',
  'https://manhwatop.net/manhwa/rain-dogs',
  'https://manhwatop.net/manhwa/barcelona-at-dawn',
  'https://manhwatop.net/manhwa/little-lizzie-1953',
  'https://manhwatop.net/manhwa/the-adventures-of-the-mad-tsar',
  'https://manhwatop.net/manhwa/little-lenny',
  'https://manhwatop.net/manhwa/micra-mind-controlled-remote-automaton',
  'https://manhwatop.net/manhwa/the-incredible-adventures-of-dog-mendonca-and-pizzaboy',
  'https://manhwatop.net/manhwa/all-true-crime-cases',
  'https://manhwatop.net/manhwa/cycops',
  'https://manhwatop.net/manhwa/aramis',
  'https://manhwatop.net/manhwa/batman-urban-legends',
  'https://manhwatop.net/manhwa/the-joker-2021',
  'https://manhwatop.net/manhwa/brindille',
  'https://manhwatop.net/manhwa/romances-of-molly-manton',
  'https://manhwatop.net/manhwa/it-takes-a-wizard',
  'https://manhwatop.net/manhwa/sigurd-vigdis',
  'https://manhwatop.net/manhwa/sweetie-pie',
  'https://manhwatop.net/manhwa/film-funnies',
  'https://manhwatop.net/manhwa/children-of-the-atom',
  'https://manhwatop.net/manhwa/karmen-2021',
  'https://manhwatop.net/manhwa/bv-friends-forever-spring-break',
  'https://manhwatop.net/manhwa/deadpool-nerdy-30',
  'https://manhwatop.net/manhwa/the-locker-room',
  'https://manhwatop.net/manhwa/god-of-war-fallen-god',
  'https://manhwatop.net/manhwa/proctor-valley-road',
  'https://manhwatop.net/manhwa/thor-loki-double-trouble',
  'https://manhwatop.net/manhwa/non-stop-spider-man',
  'https://manhwatop.net/manhwa/drawing-from-life',
  'https://manhwatop.net/manhwa/the-mad-monk',
  'https://manhwatop.net/manhwa/tom-judge-end-of-days',
  'https://manhwatop.net/manhwa/you-cant-just-kiss-anyone-you-want',
  'https://manhwatop.net/manhwa/the-complete-elfquest',
  'https://manhwatop.net/manhwa/falls-the-gotham-rain',
  'https://manhwatop.net/manhwa/marie-antoinette-phantom-queen',
  'https://manhwatop.net/manhwa/the-adventures-of-jodelle',
  'https://manhwatop.net/manhwa/another-chance-to-get-it-right',
  'https://manhwatop.net/manhwa/valkyrie-2012',
  'https://manhwatop.net/manhwa/little-lana',
  'https://manhwatop.net/manhwa/loveland',
  'https://manhwatop.net/manhwa/the-lost-path',
  'https://manhwatop.net/manhwa/drawn-quarterly-2000',
  'https://manhwatop.net/manhwa/bob-marley-tale-of-the-tuff-gong',
  'https://manhwatop.net/manhwa/brute-babe-the-infinity-of-warriors',
  'https://manhwatop.net/manhwa/grease-bats',
  'https://manhwatop.net/manhwa/infinite-frontier',
  'https://manhwatop.net/manhwa/crime-syndicate',
  'https://manhwatop.net/manhwa/crawl-space-2017',
  'https://manhwatop.net/manhwa/billy-ray-cyrus',
  'https://manhwatop.net/manhwa/official-true-crime-cases',
  'https://manhwatop.net/manhwa/tura-satana',
  'https://manhwatop.net/manhwa/to-drink-and-to-eat',
  'https://manhwatop.net/manhwa/the-last-fall',
  'https://manhwatop.net/manhwa/the-swamp-thing',
  'https://manhwatop.net/manhwa/hard-melody',
  'https://manhwatop.net/manhwa/drawing-lines-an-anthology-of-women-cartoonists',
  'https://manhwatop.net/manhwa/onyx-fight',
  'https://manhwatop.net/manhwa/jack-kirbys-silver-star',
  'https://manhwatop.net/manhwa/more-heroes-of-the-comics-portraits-of-the-legends-of-comic-books',
  'https://manhwatop.net/manhwa/nocterra',
  'https://manhwatop.net/manhwa/rick-and-morty-worlds-apart',
  'https://manhwatop.net/manhwa/brzrkr',
  'https://manhwatop.net/manhwa/james-bond-agent-of-spectre',
  'https://manhwatop.net/manhwa/jonna-and-the-unpossible-monsters',
  'https://manhwatop.net/manhwa/beware-the-witchs-shadow-winter-special',
  'https://manhwatop.net/manhwa/america-chavez-made-in-the-usa',
  'https://manhwatop.net/manhwa/chariot',
  'https://manhwatop.net/manhwa/demon-days-x-men',
  'https://manhwatop.net/manhwa/nottingham',
  'https://manhwatop.net/manhwa/myths-legends-quarterly-dark-princess',
  'https://manhwatop.net/manhwa/dead-dogs-bite',
  'https://manhwatop.net/manhwa/stringers',
  'https://manhwatop.net/manhwa/dark-stories',
  'https://manhwatop.net/manhwa/bramble',
  'https://manhwatop.net/manhwa/dragonseed',
  'https://manhwatop.net/manhwa/daddy-lost-his-head-and-other-stories',
  'https://manhwatop.net/manhwa/lancelot-link-secret-chimp',
  'https://manhwatop.net/manhwa/the-residents-freak-show',
  'https://manhwatop.net/manhwa/suicide-squad-2021',
  'https://manhwatop.net/manhwa/amazing-spider-man-the-gauntlet-the-complete-collection',
  'https://manhwatop.net/manhwa/chninkel',
  'https://manhwatop.net/manhwa/world-of-suspense',
  'https://manhwatop.net/manhwa/the-terminator-one-shot',
  'https://manhwatop.net/manhwa/juliet-takes-a-breath',
  'https://manhwatop.net/manhwa/magical-history-tour',
  'https://manhwatop.net/manhwa/the-hunting-accident-a-true-story-of-crime-and-poetry',
  'https://manhwatop.net/manhwa/love-dramas',
  'https://manhwatop.net/manhwa/fantoman',
  'https://manhwatop.net/manhwa/black-squares-on-white-pieces',
  'https://manhwatop.net/manhwa/doctor-who-graphic-novel',
  'https://manhwatop.net/manhwa/the-life-of-groo',
  'https://manhwatop.net/manhwa/caliber-presents',
  'https://manhwatop.net/manhwa/generations-forged',
  'https://manhwatop.net/manhwa/future-state-superman-house-of-el',
  'https://manhwatop.net/manhwa/the-grackle',
  'https://manhwatop.net/manhwa/the-next-batman-second-son',
  'https://manhwatop.net/manhwa/marsupilami-the-beast',
  'https://manhwatop.net/manhwa/nubia-real-one',
  'https://manhwatop.net/manhwa/wahcommo',
  'https://manhwatop.net/manhwa/captain-marvel-marvels-snapshots',
  'https://manhwatop.net/manhwa/marvels-voices-legacy',
  'https://manhwatop.net/manhwa/stray-dogs',
  'https://manhwatop.net/manhwa/two-moons',
  'https://manhwatop.net/manhwa/nuclear-family',
  'https://manhwatop.net/manhwa/moon-maid-three-keys',
  'https://manhwatop.net/manhwa/firefly-watch-how-i-soar',
  'https://manhwatop.net/manhwa/buffy-the-vampire-slayer-faith',
  'https://manhwatop.net/manhwa/kriss-of-valnor-alliances',
  'https://manhwatop.net/manhwa/detective-eye',
  'https://manhwatop.net/manhwa/love-secrets',
  'https://manhwatop.net/manhwa/love-tales',
  'https://manhwatop.net/manhwa/famous-first-edition',
  'https://manhwatop.net/manhwa/the-terrible-pope',
  'https://manhwatop.net/manhwa/the-scorpions-of-the-desert',
  'https://manhwatop.net/manhwa/love-trails',
  'https://manhwatop.net/manhwa/world-of-mystery',
  'https://manhwatop.net/manhwa/masked-marvel',
  'https://manhwatop.net/manhwa/new-super-man-the-justice-league-of-china',
  'https://manhwatop.net/manhwa/mermin',
  'https://manhwatop.net/manhwa/buddy-longway',
  'https://manhwatop.net/manhwa/tko-shorts',
  'https://manhwatop.net/manhwa/milos-world-2020',
  'https://manhwatop.net/manhwa/seen-the-true-stories-of-marginalized-trailblazers',
  'https://manhwatop.net/manhwa/sergio-aragones-groo-mightier-than-the-sword',
  'https://manhwatop.net/manhwa/the-night',
  'https://manhwatop.net/manhwa/automaton',
  'https://manhwatop.net/manhwa/brain-bats-of-venus-the-life-and-comics-of-basil-wolverton',
  'https://manhwatop.net/manhwa/thor-vs-beast-women-from-the-center-of-the-earth',
  'https://manhwatop.net/manhwa/icaro',
  'https://manhwatop.net/manhwa/marvel-mystery-comics-1943',
  'https://manhwatop.net/manhwa/shadow-reavers',
  'https://manhwatop.net/manhwa/mooncop',
  'https://manhwatop.net/manhwa/judomaster',
  'https://manhwatop.net/manhwa/marvel-western-strange-westerns-starring-the-black-rider',
  'https://manhwatop.net/manhwa/girl-comics-1949',
  'https://manhwatop.net/manhwa/a-shining-beacon',
  'https://manhwatop.net/manhwa/camp-spirit',
  'https://manhwatop.net/manhwa/blessed-thistle',
  'https://manhwatop.net/manhwa/pebbles-bamm-bamm',
  'https://manhwatop.net/manhwa/marvel-action-origins',
  'https://manhwatop.net/manhwa/sambre',
  'https://manhwatop.net/manhwa/nickelodeon-avatar-the-last-airbender-toph-beifongs-metalbending-academy',
  'https://manhwatop.net/manhwa/aria-heavenly-creatures',
  'https://manhwatop.net/manhwa/savage-2021',
  'https://manhwatop.net/manhwa/immortal-hulk-flatline',
  'https://manhwatop.net/manhwa/gi-joe-castle-fall',
  'https://manhwatop.net/manhwa/grimm-universe-presents-quarterly-darkwatchers',
  'https://manhwatop.net/manhwa/x-men-legends',
  'https://manhwatop.net/manhwa/shadow-doctor',
  'https://manhwatop.net/manhwa/go-man',
  'https://manhwatop.net/manhwa/nerve',
  'https://manhwatop.net/manhwa/pervert-pappy',
  'https://manhwatop.net/manhwa/heavy-vinyl-y2k-o',
  'https://manhwatop.net/manhwa/young-hellboy',
  'https://manhwatop.net/manhwa/super-friends-special',
  'https://manhwatop.net/manhwa/my-diary',
  'https://manhwatop.net/manhwa/my-love-1949',
  'https://manhwatop.net/manhwa/our-love',
  'https://manhwatop.net/manhwa/her-bark-her-bite',
  'https://manhwatop.net/manhwa/orphan-blade',
  'https://manhwatop.net/manhwa/the-northern-dark',
  'https://manhwatop.net/manhwa/the-days-that-disappear',
  'https://manhwatop.net/manhwa/the-ballad-of-halo-jones-1986',
  'https://manhwatop.net/manhwa/demons-tails',
  'https://manhwatop.net/manhwa/forgotten-realms-the-halflings-gem',
  'https://manhwatop.net/manhwa/honeymoon',
  'https://manhwatop.net/manhwa/black-magic',
  'https://manhwatop.net/manhwa/strong-female-protagonist',
  'https://manhwatop.net/manhwa/pyrenee',
  'https://manhwatop.net/manhwa/my-girl-pearl',
  'https://manhwatop.net/manhwa/my-friend-irma',
  'https://manhwatop.net/manhwa/the-great-wiz-and-the-ruckus',
  'https://manhwatop.net/manhwa/super-dc-giant',
  'https://manhwatop.net/manhwa/chicanos',
  'https://manhwatop.net/manhwa/aleister-crowley-wandering-the-waste',
  'https://manhwatop.net/manhwa/peanuts-a-tribute-to-charles-m-schulz',
  'https://manhwatop.net/manhwa/lolas-super-club',
  'https://manhwatop.net/manhwa/love-classics',
  'https://manhwatop.net/manhwa/sobek',
  'https://manhwatop.net/manhwa/guardians-of-the-galaxy-2020',
  'https://manhwatop.net/manhwa/sonic-the-hedgehog-2018',
  'https://manhwatop.net/manhwa/haha',
  'https://manhwatop.net/manhwa/savage-avengers',
  'https://manhwatop.net/manhwa/action-comics-2016',
  'https://manhwatop.net/manhwa/carnage-black-white-blood',
  'https://manhwatop.net/manhwa/alien',
  'https://manhwatop.net/manhwa/batman-black-white',
  'https://manhwatop.net/manhwa/yo-gabba-gabba-gabba-ball',
  'https://manhwatop.net/manhwa/life-brigade',
  'https://manhwatop.net/manhwa/young-mozart',
  'https://manhwatop.net/manhwa/chance-in-hell',
  'https://manhwatop.net/manhwa/teen-titans-academy',
  'https://manhwatop.net/manhwa/harley-quinn-2021',
  'https://manhwatop.net/manhwa/anne-franks-diary-the-graphic-adaptation',
  'https://manhwatop.net/manhwa/yo-gabba-gabba-free-comic-book-day',
  'https://manhwatop.net/manhwa/bulls-eye',
  'https://manhwatop.net/manhwa/dejah-thoris-2019',
  'https://manhwatop.net/manhwa/batman-white-knight-presents-harley-quinn',
  'https://manhwatop.net/manhwa/marvel-mystery-comics-1939',
  'https://manhwatop.net/manhwa/vampirella-the-dark-powers',
  'https://manhwatop.net/manhwa/red-sonja-2019',
  'https://manhwatop.net/manhwa/vampirella-vs-purgatori',
  'https://manhwatop.net/manhwa/the-shadow-hero',
  'https://manhwatop.net/manhwa/the-complete-don-quixote',
  'https://manhwatop.net/manhwa/blazing-comics',
  'https://manhwatop.net/manhwa/tales-of-the-realm',
  'https://manhwatop.net/manhwa/green-lantern-80-years-of-the-emerald-knight-the-deluxe-edition',
  'https://manhwatop.net/manhwa/dc-goes-to-war',
  'https://manhwatop.net/manhwa/road-to-empyre-the-kreeskrull-war',
  'https://manhwatop.net/manhwa/lords-of-empyre',
  'https://manhwatop.net/manhwa/darkness-2019',
  'https://manhwatop.net/manhwa/taskmaster-2020',
  'https://manhwatop.net/manhwa/maestro-war-and-pax',
  'https://manhwatop.net/manhwa/semiautomagic',
  'https://manhwatop.net/manhwa/zonzo',
  'https://manhwatop.net/manhwa/the-mask-of-fudo',
  'https://manhwatop.net/manhwa/detective-comics-1937',
  'https://manhwatop.net/manhwa/truth-justice',
  'https://manhwatop.net/manhwa/sensational-wonder-woman',
  'https://manhwatop.net/manhwa/miles-morales-spider-man',
  'https://manhwatop.net/manhwa/black-panther-2018',
  'https://manhwatop.net/manhwa/barbalien-red-planet',
  'https://manhwatop.net/manhwa/archie-comics-double-digest',
  'https://manhwatop.net/manhwa/paradise-lost-a-graphic-novel',
  'https://manhwatop.net/manhwa/lady-baltimore-the-witch-queens',
  'https://manhwatop.net/manhwa/future-state-teen-titans-ruins',
  'https://manhwatop.net/manhwa/challenge-of-the-super-sons',
  'https://manhwatop.net/manhwa/king-in-black-one-shots',
  'https://manhwatop.net/manhwa/drawing-power-womens-stories-of-sexual-violence-harassment-and-survival',
  'https://manhwatop.net/manhwa/american-mythology-monsters',
  'https://manhwatop.net/manhwa/abbott-1973',
  'https://manhwatop.net/manhwa/nevertheless',
  'https://manhwatop.net/manhwa/super-human-resources',
  'https://manhwatop.net/manhwa/jennifer-blood-born-again',
  'https://manhwatop.net/manhwa/belle-thunder-of-gods',
  'https://manhwatop.net/manhwa/gi-joe-a-real-american-hero-snake-eyes-the-origin',
  'https://manhwatop.net/manhwa/mammoth-book-of-best-crime-comics',
  'https://manhwatop.net/manhwa/robyn-hood-cult-of-the-spider',
  'https://manhwatop.net/manhwa/orphan-and-the-five-beasts',
  'https://manhwatop.net/manhwa/the-batman-scooby-doo-mysteries',
  'https://manhwatop.net/manhwa/teenage-mutant-ninja-turtles-best-of',
  'https://manhwatop.net/manhwa/usagi-yojimbo-2019',
  'https://manhwatop.net/manhwa/the-scumbag',
  'https://manhwatop.net/manhwa/world-of-betty-veronica-digest',
  'https://manhwatop.net/manhwa/future-state-superman-vs-imperious-lex',
  'https://manhwatop.net/manhwa/batmancatwoman',
  'https://manhwatop.net/manhwa/strange-adventures-2020',
  'https://manhwatop.net/manhwa/the-other-history-of-the-dc-universe',
  'https://manhwatop.net/manhwa/the-final-girls',
  'https://manhwatop.net/manhwa/rwbyjustice-league',
  'https://manhwatop.net/manhwa/dino-beasts',
  'https://manhwatop.net/manhwa/human-stock-exchange',
  'https://manhwatop.net/manhwa/let-them-live-unpublished-tales-from-the-dc-vault',
  'https://manhwatop.net/manhwa/gung-ho-sexy-beast',
  'https://manhwatop.net/manhwa/head-lopper',
  'https://manhwatop.net/manhwa/captain-america-1968',
  'https://manhwatop.net/manhwa/whatever-happened-to-the-world-of-tomorrow',
  'https://manhwatop.net/manhwa/shadecraft',
  'https://manhwatop.net/manhwa/decorum',
  'https://manhwatop.net/manhwa/the-witcher-fading-memories',
  'https://manhwatop.net/manhwa/usagi-yojimbo-wanderers-road',
  'https://manhwatop.net/manhwa/the-union',
  'https://manhwatop.net/manhwa/the-department-of-truth',
  'https://manhwatop.net/manhwa/vengeance-of-vampirella-2019',
  'https://manhwatop.net/manhwa/the-courier-liberty-death',
  'https://manhwatop.net/manhwa/unsacred-vol-2',
  'https://manhwatop.net/manhwa/power-rangers-unlimited-heir-to-darkness',
  'https://manhwatop.net/manhwa/van-helsing-black-annis',
  'https://manhwatop.net/manhwa/marvel-action-captain-marvel-2021',
  'https://manhwatop.net/manhwa/silk-2021',
  'https://manhwatop.net/manhwa/13-chambers',
  'https://manhwatop.net/manhwa/essential-judge-dredd-the-apocalypse-war',
  'https://manhwatop.net/manhwa/tijuana-bibles-art-and-wit-in-americas-forbidden-funnies-1930s-1950s',
  'https://manhwatop.net/manhwa/izuna',
  'https://manhwatop.net/manhwa/just-imagine-stan-lee-creating-the-dc-universe',
  'https://manhwatop.net/manhwa/disney-masters',
  'https://manhwatop.net/manhwa/ice-haven',
  'https://manhwatop.net/manhwa/si-lewens-parade-an-artists-odyssey',
  'https://manhwatop.net/manhwa/goddamn-this-war',
  'https://manhwatop.net/manhwa/michel-vaillant',
  'https://manhwatop.net/manhwa/persephone-2017',
  'https://manhwatop.net/manhwa/you-are-there',
  'https://manhwatop.net/manhwa/a-sister',
  'https://manhwatop.net/manhwa/legends-of-the-dark-knight',
  'https://manhwatop.net/manhwa/batman-66-meets-the-green-hornet-ii',
  'https://manhwatop.net/manhwa/cerebus',
  'https://manhwatop.net/manhwa/edgeworld-sand',
  'https://manhwatop.net/manhwa/dynamo-5-holiday-special-2010',
  'https://manhwatop.net/manhwa/black-comix-returns',
  'https://manhwatop.net/manhwa/fruit-of-knowledge-the-vulva-vs-the-patriarchy',
  'https://manhwatop.net/manhwa/pussey',
  'https://manhwatop.net/manhwa/the-little-book-of-knowledge-new-hollywood',
  'https://manhwatop.net/manhwa/the-black-project',
  'https://manhwatop.net/manhwa/little-nemo-in-slumberland',
  'https://manhwatop.net/manhwa/nemo-the-classic-comics-library',
  'https://manhwatop.net/manhwa/aggretsuko-meet-her-world',
  'https://manhwatop.net/manhwa/project-patron',
  'https://manhwatop.net/manhwa/the-little-book-of-knowledge-tattoos',
  'https://manhwatop.net/manhwa/dull-margaret',
  'https://manhwatop.net/manhwa/the-smithsonian-collection-of-newspaper-comics',
  'https://manhwatop.net/manhwa/marauders',
  'https://manhwatop.net/manhwa/buffy-the-vampire-slayer',
  'https://manhwatop.net/manhwa/star-wars-the-high-republic-adventures',
  'https://manhwatop.net/manhwa/star-wars-the-high-republic-behind-the-scenes-exclusive',
  'https://manhwatop.net/manhwa/malinky-robot-collected-stories-and-other-bits',
  'https://manhwatop.net/manhwa/little-book-of-knowledge-sharks',
  'https://manhwatop.net/manhwa/mindviscosity',
  'https://manhwatop.net/manhwa/witchblood',
  'https://manhwatop.net/manhwa/blackbird-days',
  'https://manhwatop.net/manhwa/star-wars-the-high-republic',
  'https://manhwatop.net/manhwa/micronauts-1979',
  'https://manhwatop.net/manhwa/wings-of-fire',
  'https://manhwatop.net/manhwa/hope-for-the-future',
  'https://manhwatop.net/manhwa/crashpad',
  'https://manhwatop.net/manhwa/the-rook-desperate-times',
  'https://manhwatop.net/manhwa/the-instinct-for-cooperation-a-graphic-novel-conversation-with-noam-chomsky',
  'https://manhwatop.net/manhwa/carbon-silicon',
  'https://manhwatop.net/manhwa/showa-a-history-of-japan',
  'https://manhwatop.net/manhwa/official-rip-kirby',
  'https://manhwatop.net/manhwa/titan-1992',
  'https://manhwatop.net/manhwa/king-in-black',
  'https://manhwatop.net/manhwa/the-question-2005',
  'https://manhwatop.net/manhwa/geiger',
  'https://manhwatop.net/manhwa/black-blizzard',
  'https://manhwatop.net/manhwa/low-society',
  'https://manhwatop.net/manhwa/slaine-the-brutania-chronicles',
  'https://manhwatop.net/manhwa/a-gift-for-a-ghost',
  'https://manhwatop.net/manhwa/the-age-of-selfishness-ayn-rand-morality-and-the-financial-crisis',
  'https://manhwatop.net/manhwa/superman-rebirth-deluxe-edition',
  'https://manhwatop.net/manhwa/avengers-2018',
  'https://manhwatop.net/manhwa/venom-2018',
  'https://manhwatop.net/manhwa/wanted-lucky-luke',
  'https://manhwatop.net/manhwa/skull-island-the-birth-of-kong',
  'https://manhwatop.net/manhwa/the-dreaming-waking-hours',
  'https://manhwatop.net/manhwa/jokerharley-criminal-sanity',
  'https://manhwatop.net/manhwa/spider-man-the-spiders-shadow',
  'https://manhwatop.net/manhwa/phantom-on-the-scan',
  'https://manhwatop.net/manhwa/grimm-tales-of-terror-quarterly-hh-holmes',
  'https://manhwatop.net/manhwa/the-silver-coin',
  'https://manhwatop.net/manhwa/the-cimmerian-iron-shadows-in-the-moon',
  'https://manhwatop.net/manhwa/the-resistance-uprising',
  'https://manhwatop.net/manhwa/blue-spring',
  'https://manhwatop.net/manhwa/the-thousand-deaths-of-baron-von-donut',
  'https://manhwatop.net/manhwa/diabolical-summer',
  'https://manhwatop.net/manhwa/mean-girls-club',
  'https://manhwatop.net/manhwa/rick-and-morty-presents-jerryboree',
  'https://manhwatop.net/manhwa/rick-and-morty-presents-death-stalkers',
  'https://manhwatop.net/manhwa/mpls-sound',
  'https://manhwatop.net/manhwa/kill-my-mother',
  'https://manhwatop.net/manhwa/run-wild',
  'https://manhwatop.net/manhwa/alone-2017',
  'https://manhwatop.net/manhwa/komodo-and-the-defiants',
  'https://manhwatop.net/manhwa/phase-one',
  'https://manhwatop.net/manhwa/true-complete-mystery',
  'https://manhwatop.net/manhwa/romances-of-the-west',
  'https://manhwatop.net/manhwa/my-little-pony-friendship-is-magic',
  'https://manhwatop.net/manhwa/jsa-our-worlds-at-war',
  'https://manhwatop.net/manhwa/ana-and-the-cosmic-race',
  'https://manhwatop.net/manhwa/betty-veronica-the-bond-of-friendship',
  'https://manhwatop.net/manhwa/steampunk-swimsuit',
  'https://manhwatop.net/manhwa/disney-tangled-the-story-of-the-movie-in-comics',
  'https://manhwatop.net/manhwa/conspiracy-black-knight-satellite',
  'https://manhwatop.net/manhwa/conspiracy-planet-x',
  'https://manhwatop.net/manhwa/above-the-dreamless-dead',
  'https://manhwatop.net/manhwa/bionic',
  'https://manhwatop.net/manhwa/arthur-sex',
  'https://manhwatop.net/manhwa/smart-bomb',
  'https://manhwatop.net/manhwa/doctor-strange-1974',
  'https://manhwatop.net/manhwa/over-the-ropes',
  'https://manhwatop.net/manhwa/jason-conquers-america',
  'https://manhwatop.net/manhwa/keen-detective-funnies',
  'https://manhwatop.net/manhwa/a-matter-of-life',
  'https://manhwatop.net/manhwa/godzilla-vs-barkley',
  'https://manhwatop.net/manhwa/wrinkles',
  'https://manhwatop.net/manhwa/earthlore-reign-of-the-dragon-lord',
  'https://manhwatop.net/manhwa/boo-halloween-stories-2013',
  'https://manhwatop.net/manhwa/boo-halloween-stories-2014',
  'https://manhwatop.net/manhwa/1000-storms',
  'https://manhwatop.net/manhwa/justice-league-2018',
  'https://manhwatop.net/manhwa/green-lantern-2021',
  'https://manhwatop.net/manhwa/man-bat-2021',
  'https://manhwatop.net/manhwa/batmanfortnite-zero-point',
  'https://manhwatop.net/manhwa/magna-man-the-last-superhero',
  'https://manhwatop.net/manhwa/comics-revue',
  'https://manhwatop.net/manhwa/pale-horse',
  'https://manhwatop.net/manhwa/eureka',
  'https://manhwatop.net/manhwa/mechanics',
  'https://manhwatop.net/manhwa/american-welding-society-iron-man-special',
  'https://manhwatop.net/manhwa/la-muerta-vengeance',
  'https://manhwatop.net/manhwa/la-muerta-retribution',
  'https://manhwatop.net/manhwa/la-muerta-ascension',
  'https://manhwatop.net/manhwa/spin-angels',
  'https://manhwatop.net/manhwa/phantom-2040',
  'https://manhwatop.net/manhwa/jeff-job-hunter',
  'https://manhwatop.net/manhwa/fight',
  'https://manhwatop.net/manhwa/fight2',
  'https://manhwatop.net/manhwa/wonder-duck',
  'https://manhwatop.net/manhwa/its-a-ducks-life',
  'https://manhwatop.net/manhwa/lost-in-the-future',
  'https://manhwatop.net/manhwa/maelstrom',
  'https://manhwatop.net/manhwa/underground-1987',
  'https://manhwatop.net/manhwa/blood-queen-vs-dracula',
  'https://manhwatop.net/manhwa/winterworld-frozen-fleet',
  'https://manhwatop.net/manhwa/avengerssquadron-supreme-98',
  'https://manhwatop.net/manhwa/rivers-of-london-monday-monday',
  'https://manhwatop.net/manhwa/free-comic-book-day-2021',
  'https://manhwatop.net/manhwa/pellucidar-across-savage-seas',
  'https://manhwatop.net/manhwa/technofreak',
  'https://manhwatop.net/manhwa/transformers-shattered-glass',
  'https://manhwatop.net/manhwa/beyond-the-farthest-star-warriors-of-zandar',
  'https://manhwatop.net/manhwa/cable-reloaded',
  'https://manhwatop.net/manhwa/king-spawn',
  'https://manhwatop.net/manhwa/echolands',
  'https://manhwatop.net/manhwa/thirteen-steps',
  'https://manhwatop.net/manhwa/strangers-in-paradise-1993',
  'https://manhwatop.net/manhwa/guardians-of-the-galaxy-by-brian-michael-bendis',
  'https://manhwatop.net/manhwa/norse-mythology-ii',
  'https://manhwatop.net/manhwa/spider-man-life-story',
  'https://manhwatop.net/manhwa/amy-papuda',
  'https://manhwatop.net/manhwa/the-atlantis-chronicles',
  'https://manhwatop.net/manhwa/warlock-5',
  'https://manhwatop.net/manhwa/tale-of-mya-rom',
  'https://manhwatop.net/manhwa/sapphire',
  'https://manhwatop.net/manhwa/city-people-notebook',
  'https://manhwatop.net/manhwa/to-riverdale-and-back-again',
  'https://manhwatop.net/manhwa/alien-resurrection',
  'https://manhwatop.net/manhwa/firefly',
  'https://manhwatop.net/manhwa/dark-reign-lethal-legion',
  'https://manhwatop.net/manhwa/incredible-hulk-crossroads',
  'https://manhwatop.net/manhwa/skeleton-key',
  'https://manhwatop.net/manhwa/yragael-urm-the-mad',
  'https://manhwatop.net/manhwa/stark-future',
  'https://manhwatop.net/manhwa/vampyres-kiss-biancas-revenge',
  'https://manhwatop.net/manhwa/atomic-robo-and-the-shadow-from-beyond-time',
  'https://manhwatop.net/manhwa/crickets',
  'https://manhwatop.net/manhwa/blammo',
  'https://manhwatop.net/manhwa/kaijumax-deluxe-edition',
  'https://manhwatop.net/manhwa/hotwire-requiem-for-the-dead',
  'https://manhwatop.net/manhwa/the-blue-flame',
  'https://manhwatop.net/manhwa/the-beauty-all-good-things-one-shot',
  'https://manhwatop.net/manhwa/telepaths',
  'https://manhwatop.net/manhwa/robyn-hood-annual-the-swarm',
  'https://manhwatop.net/manhwa/almost-american',
  'https://manhwatop.net/manhwa/demon-days-cursed-web',
  'https://manhwatop.net/manhwa/red-sonja-2021',
  'https://manhwatop.net/manhwa/grimm-spotlight-red-agent-beast-of-belgium',
  'https://manhwatop.net/manhwa/western-winners',
  'https://manhwatop.net/manhwa/sport-stars',
  'https://manhwatop.net/manhwa/the-anthology-of-mind',
  'https://manhwatop.net/manhwa/copra-2012',
  'https://manhwatop.net/manhwa/chaos',
  'https://manhwatop.net/manhwa/transformers-2019',
  'https://manhwatop.net/manhwa/last-flight-out',
  'https://manhwatop.net/manhwa/mazebook',
  'https://manhwatop.net/manhwa/search-for-hu',
  'https://manhwatop.net/manhwa/army-of-darkness-1979',
  'https://manhwatop.net/manhwa/star-trek-the-mirror-war',
  'https://manhwatop.net/manhwa/betty-veronica-friends-forever-halloween-spooktacular',
  'https://manhwatop.net/manhwa/amazing-detective-cases',
  'https://manhwatop.net/manhwa/justice-comics-1948',
  'https://manhwatop.net/manhwa/creepy-things',
  'https://manhwatop.net/manhwa/marvel-graphic-novel-conan-of-the-isles',
  'https://manhwatop.net/manhwa/not-all-robots',
  'https://manhwatop.net/manhwa/the-unbelievable-unteens-from-the-world-of-black-hammer',
  'https://manhwatop.net/manhwa/hyper-scape-the-end-of-the-beginning',
  'https://manhwatop.net/manhwa/empyre-captain-america-the-avengers',
  'https://manhwatop.net/manhwa/space-bastards',
  'https://manhwatop.net/manhwa/spider-man-1990',
  'https://manhwatop.net/manhwa/marvel-masterworks-daredevil',
  'https://manhwatop.net/manhwa/funny-frolics',
  'https://manhwatop.net/manhwa/ziggy-pig-silly-seal-comics-1944',
  'https://manhwatop.net/manhwa/i-survived',
  'https://manhwatop.net/manhwa/yang',
  'https://manhwatop.net/manhwa/journey-into-unknown-worlds-1950',
  'https://manhwatop.net/manhwa/whip-wilson',
  'https://manhwatop.net/manhwa/shang-chi-infinity-comic',
  'https://manhwatop.net/manhwa/ms-marvel-infinity-comic-primer',
  'https://manhwatop.net/manhwa/moon-knight-infinity-comic-primer',
  'https://manhwatop.net/manhwa/moon-girl-and-devil-dinosaur-infinity-comic-primer',
  'https://manhwatop.net/manhwa/its-jeff-infinity-comic',
  'https://manhwatop.net/manhwa/giant-size-little-marvels-infinity-comic',
  'https://manhwatop.net/manhwa/captain-marvel-infinity-comic-primer',
  'https://manhwatop.net/manhwa/black-widow-infinity-comic',
  'https://manhwatop.net/manhwa/black-panther-infinity-comic-primer',
  'https://manhwatop.net/manhwa/amazing-fantasy-infinity-comic-prelude',
  'https://manhwatop.net/manhwa/wildstorm-swimsuit-special',
  'https://manhwatop.net/manhwa/wildstorm-swimsuit-97',
  'https://manhwatop.net/manhwa/all-hallows-eve',
  'https://manhwatop.net/manhwa/jurassic-park-raptors-hijack',
  'https://manhwatop.net/manhwa/red-warrior',
  'https://manhwatop.net/manhwa/private-eye',
  'https://manhwatop.net/manhwa/cavewoman-he-said-she-said',
  'https://manhwatop.net/manhwa/cavewoman-red-menace',
  'https://manhwatop.net/manhwa/cavewoman-uncovered-pinup-book-budd-root-special-edition',
  'https://manhwatop.net/manhwa/harbinger-wars-2',
  'https://manhwatop.net/manhwa/heroes-for-hire-1997',
  'https://manhwatop.net/manhwa/the-shaolin-cowboy-wholl-stop-the-reign',
  'https://manhwatop.net/manhwa/batman-80-years-of-the-bat-family',
  'https://manhwatop.net/manhwa/unearthed-a-jessica-cruz-story',
  'https://manhwatop.net/manhwa/titans-united',
  'https://manhwatop.net/manhwa/batman-day',
  'https://manhwatop.net/manhwa/strange-nation',
  'https://manhwatop.net/manhwa/straitjacket',
  'https://manhwatop.net/manhwa/american-woman',
  'https://manhwatop.net/manhwa/noir-a-collection-of-crime-comics',
  'https://manhwatop.net/manhwa/c-m-o-comics',
  'https://manhwatop.net/manhwa/star-comics',
  'https://manhwatop.net/manhwa/the-world-of-black-hammer-library-edition',
  'https://manhwatop.net/manhwa/man-eaters-the-cursed',
  'https://manhwatop.net/manhwa/godkiller-tomorrows-ashes',
  'https://manhwatop.net/manhwa/savage-hearts',
  'https://manhwatop.net/manhwa/save-yourself',
  'https://manhwatop.net/manhwa/warhammer-40000-sisters-of-battle',
  'https://manhwatop.net/manhwa/web-of-spider-man',
  'https://manhwatop.net/manhwa/x-men-the-trial-of-magneto',
  'https://manhwatop.net/manhwa/the-walking-dead-deluxe',
  'https://manhwatop.net/manhwa/wynd',
  'https://manhwatop.net/manhwa/time-before-time',
  'https://manhwatop.net/manhwa/maw',
  'https://manhwatop.net/manhwa/hellboy-and-the-bprd-1957-family-ties',
  'https://manhwatop.net/manhwa/interview-with-the-vampire-claudias-story',
  'https://manhwatop.net/manhwa/razorblades-the-horror-magazine',
  'https://manhwatop.net/manhwa/i-walk-with-monsters',
  'https://manhwatop.net/manhwa/star-wars-war-of-the-bounty-hunters-boushh',
  'https://manhwatop.net/manhwa/primordial',
  'https://manhwatop.net/manhwa/vampiverse',
  'https://manhwatop.net/manhwa/the-mask-toys-in-the-attic',
  'https://manhwatop.net/manhwa/silent-screamers-nosferatu-1922',
  'https://manhwatop.net/manhwa/x-men-unlimited-infinity-comic',
  'https://manhwatop.net/manhwa/star-wars-the-high-republic-adventures-the-monster-of-temple-peak',
  'https://manhwatop.net/manhwa/the-last-annihilation',
  'https://manhwatop.net/manhwa/space-worlds',
  'https://manhwatop.net/manhwa/speed-carter-spaceman',
  'https://manhwatop.net/manhwa/pandora',
  'https://manhwatop.net/manhwa/eternity-triple-action',
  'https://manhwatop.net/manhwa/cosmic-heroes',
  'https://manhwatop.net/manhwa/pandoras-legacy',
  'https://manhwatop.net/manhwa/extraordinary',
  'https://manhwatop.net/manhwa/aliens-glass-corridor',
  'https://manhwatop.net/manhwa/nine-volt',
  'https://manhwatop.net/manhwa/dreadstar-returns',
  'https://manhwatop.net/manhwa/leather-lace-1989',
  'https://manhwatop.net/manhwa/book-of-death-fall-of-bloodshot',
  'https://manhwatop.net/manhwa/good-night-hem',
  'https://manhwatop.net/manhwa/first-degree-a-crime-anthology',
  'https://manhwatop.net/manhwa/he-who-fights-with-monsters',
  'https://manhwatop.net/manhwa/innovation-spectacular',
  'https://manhwatop.net/manhwa/hero-alliance-quarterly',
  'https://manhwatop.net/manhwa/x-men-onslaught-revelation',
  'https://manhwatop.net/manhwa/death-of-doctor-strange',
  'https://manhwatop.net/manhwa/star-wars-adventures-ghosts-of-vaders-castle',
  'https://manhwatop.net/manhwa/runes',
  'https://manhwatop.net/manhwa/frontiersman',
  'https://manhwatop.net/manhwa/free-comic-book-day-2020',
  'https://manhwatop.net/manhwa/red-room',
  'https://manhwatop.net/manhwa/starchild-mythopolis',
  'https://manhwatop.net/manhwa/cimarronin-fall-of-the-cross',
  'https://manhwatop.net/manhwa/the-black-canary-bird-of-prey',
  'https://manhwatop.net/manhwa/arrowhead',
  'https://manhwatop.net/manhwa/dcs-greatest-detective-stories-ever-told',
  'https://manhwatop.net/manhwa/the-westwood-witches',
  'https://manhwatop.net/manhwa/the-monkey-and-the-bear',
  'https://manhwatop.net/manhwa/starchild-crossroads',
  'https://manhwatop.net/manhwa/aphrodisia',
  'https://manhwatop.net/manhwa/pvp',
  'https://manhwatop.net/manhwa/batman-66-i',
  'https://manhwatop.net/manhwa/searchers',
  'https://manhwatop.net/manhwa/searchers-apostle-of-mercy',
  'https://manhwatop.net/manhwa/samurai-1987',
  'https://manhwatop.net/manhwa/dragonring-1987',
  'https://manhwatop.net/manhwa/86-voltz-the-dead-girl',
  'https://manhwatop.net/manhwa/north-bend',
  'https://manhwatop.net/manhwa/normalman-megaton-man-special',
  'https://manhwatop.net/manhwa/buffy-the-vampire-slayer-1998',
  'https://manhwatop.net/manhwa/witch-special',
  'https://manhwatop.net/manhwa/teen-titans-2016',
  'https://manhwatop.net/manhwa/swing',
  'https://manhwatop.net/manhwa/history-comics-the-great-chicago-fire-rising-from-the-ashes',
  'https://manhwatop.net/manhwa/investigators',
  'https://manhwatop.net/manhwa/stupid-stupid-rat-tails',
  'https://manhwatop.net/manhwa/doctor-strange-epic-collection-alone-against-eternity',
  'https://manhwatop.net/manhwa/namor-visionaries-john-byrne',
  'https://manhwatop.net/manhwa/thing-classic',
  'https://manhwatop.net/manhwa/shadowalker',
  'https://manhwatop.net/manhwa/vampyres',
  'https://manhwatop.net/manhwa/broken-bear',
  'https://manhwatop.net/manhwa/the-question-1987',
  'https://manhwatop.net/manhwa/iyanu-child-of-wonder',
  'https://manhwatop.net/manhwa/reign-of-x',
  'https://manhwatop.net/manhwa/monsters-myths-and-marvels',
  'https://manhwatop.net/manhwa/kissnation',
  'https://manhwatop.net/manhwa/3-d-tales-of-the-west',
  'https://manhwatop.net/manhwa/battleground',
  'https://manhwatop.net/manhwa/shadow-life',
  'https://manhwatop.net/manhwa/kairos-2020',
  'https://manhwatop.net/manhwa/the-darkest-hour',
  'https://manhwatop.net/manhwa/shadowplay',
  'https://manhwatop.net/manhwa/batmansuperman-2019',
  'https://manhwatop.net/manhwa/detective-comics-2016',
  'https://manhwatop.net/manhwa/checkmate-2021',
  'https://manhwatop.net/manhwa/batman-reptilian',
  'https://manhwatop.net/manhwa/robin-2021',
  'https://manhwatop.net/manhwa/wonder-woman-black-gold',
  'https://manhwatop.net/manhwa/robyn-hood-night-of-the-hunter',
  'https://manhwatop.net/manhwa/children-of-the-plague',
  'https://manhwatop.net/manhwa/10-years-to-death',
  'https://manhwatop.net/manhwa/police-action',
  'https://manhwatop.net/manhwa/worlds-greatest-songs',
  'https://manhwatop.net/manhwa/hauteville-house',
  'https://manhwatop.net/manhwa/backstreet-project',
  'https://manhwatop.net/manhwa/wonderland-annual-reign-of-madness',
  'https://manhwatop.net/manhwa/transformers-halloween-special',
  'https://manhwatop.net/manhwa/the-phantom-twin',
  'https://manhwatop.net/manhwa/blade-runner-2029',
  'https://manhwatop.net/manhwa/battlecats-2021',
  'https://manhwatop.net/manhwa/dejah-thoris-vs-john-carter-of-mars',
  'https://manhwatop.net/manhwa/adventureman',
  'https://manhwatop.net/manhwa/gi-joe-a-real-american-hero-yearbook-2021',
  'https://manhwatop.net/manhwa/venom-carnage-infinity-comic',
  'https://manhwatop.net/manhwa/deceivers',
  'https://manhwatop.net/manhwa/two-redheads-a-dead-blonde',
  'https://manhwatop.net/manhwa/billy-buckskin-western',
  'https://manhwatop.net/manhwa/navy-combat',
  'https://manhwatop.net/manhwa/crime-fighters',
  'https://manhwatop.net/manhwa/police-badge-479',
  'https://manhwatop.net/manhwa/vision-the-scarlet-witch-the-saga-of-wanda-and-vision',
  'https://manhwatop.net/manhwa/ultimates-by-al-ewing-the-complete-collection',
  'https://manhwatop.net/manhwa/all-new-x-factor',
  'https://manhwatop.net/manhwa/the-demon-1990',
  'https://manhwatop.net/manhwa/heroes-for-hire-2011',
  'https://manhwatop.net/manhwa/avengers-west-coast-epic-collection',
  'https://manhwatop.net/manhwa/deadpool-infinity-comic',
  'https://manhwatop.net/manhwa/spider-man-the-road-to-venom',
  'https://manhwatop.net/manhwa/devil-dog-dugan',
  'https://manhwatop.net/manhwa/caught',
  'https://manhwatop.net/manhwa/grave-danger',
  'https://manhwatop.net/manhwa/the-fang',
  'https://manhwatop.net/manhwa/archie-halloween-spectacular',
  'https://manhwatop.net/manhwa/chicken-devil',
  'https://manhwatop.net/manhwa/mass-effect-the-complete-comics',
  'https://manhwatop.net/manhwa/jennifer-blood-2021',
  'https://manhwatop.net/manhwa/dirtbag-rapture',
  'https://manhwatop.net/manhwa/eternals-celestia',
  'https://manhwatop.net/manhwa/new-mutants-2019',
  'https://manhwatop.net/manhwa/a-righteous-thirst-for-vengeance',
  'https://manhwatop.net/manhwa/belle-headless-horseman',
  'https://manhwatop.net/manhwa/hey-kids-comics-vol-2-prophets-loss',
  'https://manhwatop.net/manhwa/sergeant-barney-barker',
  'https://manhwatop.net/manhwa/the-murder-of-king-tut',
  'https://manhwatop.net/manhwa/this-was-our-pact',
  'https://manhwatop.net/manhwa/psychodrama-illustrated',
  'https://manhwatop.net/manhwa/old-wounds',
  'https://manhwatop.net/manhwa/solitary',
  'https://manhwatop.net/manhwa/strange-galaxy',
  'https://manhwatop.net/manhwa/fem-fantastique',
  'https://manhwatop.net/manhwa/strange-attractors-moon-fever',
  'https://manhwatop.net/manhwa/ghost-rider-kushala-infinity-comic',
  'https://manhwatop.net/manhwa/suicide-squad-king-shark',
  'https://manhwatop.net/manhwa/cicis-journal-the-adventures-of-a-writer-in-training',
  'https://manhwatop.net/manhwa/the-wednesday-conspiracy',
  'https://manhwatop.net/manhwa/smoke-and-mirrors',
  'https://manhwatop.net/manhwa/cloaks',
  'https://manhwatop.net/manhwa/displacement',
  'https://manhwatop.net/manhwa/delilah-dirk-and-the-turkish-lieutenant',
  'https://manhwatop.net/manhwa/adventurers-1989',
  'https://manhwatop.net/manhwa/fright',
  'https://manhwatop.net/manhwa/aliens-kidnapped',
  'https://manhwatop.net/manhwa/donarr-the-unyielding',
  'https://manhwatop.net/manhwa/fractured',
  'https://manhwatop.net/manhwa/mighty-marvel-holiday-special-halloween-with-the-rhino-infinity-comic',
  'https://manhwatop.net/manhwa/beetlejuice',
  'https://manhwatop.net/manhwa/primordial-2021',
  'https://manhwatop.net/manhwa/sultry-teenage-super-foxes',
  'https://manhwatop.net/manhwa/the-walking-dead-1989',
  'https://manhwatop.net/manhwa/charlton-action-featuring-static',
  'https://manhwatop.net/manhwa/nocturnals-omnibus',
  'https://manhwatop.net/manhwa/bacon-and-other-monstrous-tales',
  'https://manhwatop.net/manhwa/untold-horror',
  'https://manhwatop.net/manhwa/madman-library-edition',
  'https://manhwatop.net/manhwa/furrlough',
  'https://manhwatop.net/manhwa/cuphead-comic-capers-curios',
  'https://manhwatop.net/manhwa/firekind',
  'https://manhwatop.net/manhwa/pocahontas-princess-of-the-new-world',
  'https://manhwatop.net/manhwa/dakkon-blackblade-a-magic-the-gathering-legend',
  'https://manhwatop.net/manhwa/kriss-of-valnor-the-mountain-of-time',
  'https://manhwatop.net/manhwa/notes-from-a-defeatist',
  'https://manhwatop.net/manhwa/coyote-doggirl',
  'https://manhwatop.net/manhwa/babel',
  'https://manhwatop.net/manhwa/haunted-2014',
  'https://manhwatop.net/manhwa/the-fantastic-voyage-of-lady-rozenbilt',
  'https://manhwatop.net/manhwa/fight-against-crime',
  'https://manhwatop.net/manhwa/all-surprise-comics',
  'https://manhwatop.net/manhwa/funny-tunes',
  'https://manhwatop.net/manhwa/china-sea',
  'https://manhwatop.net/manhwa/demon-hunter-1989',
  'https://manhwatop.net/manhwa/abyss-family-issues',
  'https://manhwatop.net/manhwa/getting-dizzy',
  'https://manhwatop.net/manhwa/crypterns-ep1',
  'https://manhwatop.net/manhwa/tales-of-terror-annual-goddess-of-death',
  'https://manhwatop.net/manhwa/vampirella-2021-holiday-special',
  'https://manhwatop.net/manhwa/the-fearsome-doctor-fang',
  'https://manhwatop.net/manhwa/bad-city-blue',
  'https://manhwatop.net/manhwa/radio-apocalypse',
  'https://manhwatop.net/manhwa/squarriors-2016',
  'https://manhwatop.net/manhwa/the-darkhold',
  'https://manhwatop.net/manhwa/my-little-pony-generations',
  'https://manhwatop.net/manhwa/clear',
  'https://manhwatop.net/manhwa/deathworld-book-two',
  'https://manhwatop.net/manhwa/i-know-what-i-am-the-life-and-times-of-artemisia-gentileschi',
  'https://manhwatop.net/manhwa/the-great-gatsby-the-graphic-novel',
  'https://manhwatop.net/manhwa/the-monkey-in-the-basement-and-other-delusions',
  'https://manhwatop.net/manhwa/the-last-contract',
  'https://manhwatop.net/manhwa/cold-blooded-chameleon-commandos',
  'https://manhwatop.net/manhwa/bravura',
  'https://manhwatop.net/manhwa/deathworld-book-three',
  'https://manhwatop.net/manhwa/meow-baby',
  'https://manhwatop.net/manhwa/marco-the-metamorphic-manatee',
  'https://manhwatop.net/manhwa/robin-batman',
  'https://manhwatop.net/manhwa/overwatch-new-blood',
  'https://manhwatop.net/manhwa/pennyworth',
  'https://manhwatop.net/manhwa/batgirls',
  'https://manhwatop.net/manhwa/future-state-gotham',
  'https://manhwatop.net/manhwa/shangri-la-2021',
  'https://manhwatop.net/manhwa/captain-america-the-movie',
  'https://manhwatop.net/manhwa/x-men-iconnect-edition',
  'https://manhwatop.net/manhwa/drawing-on-your-nightmares',
  'https://manhwatop.net/manhwa/wayne-shelton',
  'https://manhwatop.net/manhwa/betty-and-veronica-digest-magazine',
  'https://manhwatop.net/manhwa/the-return-of-shadowhawk',
  'https://manhwatop.net/manhwa/red-sonja-the-movie',
  'https://manhwatop.net/manhwa/transformers-prime',
  'https://manhwatop.net/manhwa/criminal-macabre-spirit-of-the-demon',
  'https://manhwatop.net/manhwa/betty-veronica-decades-the-1960s',
  'https://manhwatop.net/manhwa/fear-itself-youth-in-revolt',
  'https://manhwatop.net/manhwa/four-color-comics',
  'https://manhwatop.net/manhwa/josie-and-the-pussycats-1969',
  'https://manhwatop.net/manhwa/love-everlasting',
  'https://manhwatop.net/manhwa/dune-the-graphic-novel',
  'https://manhwatop.net/manhwa/the-complete-carl-barks-disney-library',
  'https://manhwatop.net/manhwa/archie-modern-classics',
  'https://manhwatop.net/manhwa/pop-gun-war-chain-letter',
  'https://manhwatop.net/manhwa/the-black-plague',
  'https://manhwatop.net/manhwa/batman-fortress',
  'https://manhwatop.net/manhwa/the-dark-room',
  'https://manhwatop.net/manhwa/the-witches-the-graphic-novel',
  'https://manhwatop.net/manhwa/bastien-vives-the-blouse',
  'https://manhwatop.net/manhwa/midnight-mover',
  'https://manhwatop.net/manhwa/amazing-fantasy-2022',
  'https://manhwatop.net/manhwa/star-trek-picard-stargazer',
  'https://manhwatop.net/manhwa/thunderbolts-2022',
  'https://manhwatop.net/manhwa/until-my-knuckles-bleed-one-deadly-shot',
  'https://manhwatop.net/manhwa/power-rangers-unlimited',
  'https://manhwatop.net/manhwa/parasomnia-the-dreaming-god',
  'https://manhwatop.net/manhwa/archies-ten-issue-collectors-set',
  'https://manhwatop.net/manhwa/archie-friends-a-timely-tale',
  'https://manhwatop.net/manhwa/misfits-of-avalon-the-queen-of-air-and-delinquency',
  'https://manhwatop.net/manhwa/batman-the-court-of-owls',
  'https://manhwatop.net/manhwa/captain-wings',
  'https://manhwatop.net/manhwa/multiversity-teen-justice',
  'https://manhwatop.net/manhwa/dark-crisis',
  'https://manhwatop.net/manhwa/night-fever',
  'https://manhwatop.net/manhwa/escobar-el-patron',
  'https://manhwatop.net/manhwa/march-of-crime',
  'https://manhwatop.net/manhwa/ex-mutants-special-consumer-electronics-show-edition',
  'https://manhwatop.net/manhwa/captain-flight-comics',
  'https://manhwatop.net/manhwa/neil-gaimans-likely-stories',
  'https://manhwatop.net/manhwa/my-story-true-romances-in-pictures',
  'https://manhwatop.net/manhwa/martin-kane-private-eye',
  'https://manhwatop.net/manhwa/x-men-before-the-fall-heralds-of-apocalypse',
]

app.use(express.static('client'));
app.use(bodyParser.json());
app.use(function (req, res, next) {
  res.header("Access-Control-Allow-Origin", '*'); // disabled for security local
  res.header("Access-Control-Allow-Headers", 'Content-Type');
  next();
});

app.get('/crawl-comics', async (req, res) => {
  console.log('url', req.query.url);
  let chapter_images = await scrapeComics(req.query.url);
  let fail = chapter_images.filter((chap) => chap == "/Content/images/blank.gif").length;
  let success = chapter_images.length - fail;

  if (fail == 0) {
    const options = {
      url: 'https://blackdog.vip/api/storage_chapter',
      'method': 'POST',
      'headers': {
        'Content-Type': 'reqapplication/jsonuest'
      },
      'body': JSON.stringify({
        "images": chapter_images,
        "comic_name": req.query.comic_name,
        "chapter_name": req.query.chapter_name
      })
    }

    request(options, function (error, response, body) {
      if (error) {
        console.log('Upload: fail');
        console.log('error: ', error);
      } else {
        console.log('Upload: success');
      }
    });
    console.log(chapter_images);
  }
  res.json({
    message: `Result:\n
    Total: ${chapter_images.length}\n
    Success: ${success}\n
    Fail: ${fail}`,
    chapter_images
  })
});

app.get('/crawl-comics-chapter', async (req, res) => {
  for (const url of listURL) {
    console.log('url', url);
    await scrapeComicsChapter(url);
  }

});

app.get('/crawl-soundtracks', async (req, res) => {
  console.log('url', req.query.url);
  console.log('film_id', req.query.film_id);
  console.log('type', req.query.type);
  console.log('slug', req.query.slug);

  let dataSoundtrack = req.query.type == 2 ? await scrapeSoundtrack(req.query.url) : await scrapeSoundtrackForShow(req.query.url);
  // console.log(dataSoundtrack);
  // return
  const formatData = []
  if (req.query.type == 2) {
    for (let i = 0; i < dataSoundtrack.length; i++) {
      if (dataSoundtrack[i].soundtrackUrl.includes("youtube")) {
        const temp = {
          name: dataSoundtrack[i].soundtrackName,
          slug: dataSoundtrack[i].soundtrackName?.toLowerCase().replace(/\s+/g, '-').replace("&", "and"),
          artist: dataSoundtrack[i].soundtrackSingle,
          youtube_link: dataSoundtrack[i].soundtrackUrl,
          film_id: req.query.film_id
        }
        formatData.push(temp)
      } else if (dataSoundtrack[i].soundtrackUrl.includes("spotify")) {
        const temp = {
          name: dataSoundtrack[i].soundtrackName,
          slug: dataSoundtrack[i].soundtrackName?.toLowerCase().replace(/\s+/g, '-').replace("&", "and"),
          artist: dataSoundtrack[i].soundtrackSingle,
          spotify_link: dataSoundtrack[i].soundtrackUrl,
          film_id: req.query.film_id
        }
        formatData.push(temp)
      } else if (dataSoundtrack[i].soundtrackUrl.includes("amazon")) {
        const temp = {
          name: dataSoundtrack[i].soundtrackName,
          slug: dataSoundtrack[i].soundtrackName?.toLowerCase().replace(/\s+/g, '-').replace("&", "and"),
          artist: dataSoundtrack[i].soundtrackSingle,
          amazon_link: dataSoundtrack[i].soundtrackUrl,
          film_id: req.query.film_id
        }
        formatData.push(temp)
      } else {
        const temp = {
          name: dataSoundtrack[i].soundtrackName,
          slug: dataSoundtrack[i].soundtrackName?.toLowerCase().replace(/\s+/g, '-').replace("&", "and"),
          artist: dataSoundtrack[i].soundtrackSingle,
          apple_link: dataSoundtrack[i].soundtrackUrl,
          film_id: req.query.film_id
        }
        formatData.push(temp)
      }
    }
    // console.log(formatData);

    // add soundtrack in db
    const postSoundtrack = await fetch(`http://45.79.198.164:5000/soundtrack/addList`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(formatData),
    });

    console.log(await postSoundtrack.json());
  } else {
    //1. add season
    const parts = req.query.url.split('/');
    const lastPart = parts[parts.length - 1];
    const match = lastPart.match(/season-\d+/);
    const seasonPart = match[0];
    const replacedTemp = seasonPart.replace(/-/g, ' ');
    const capitalizedTemp = replacedTemp.replace(/(^|\s)\S/g, function (match) {
      return match.toUpperCase();
    });
    const seasonData = {
      name: capitalizedTemp,
      slug: seasonPart,
      film_id: req.query.film_id
    }

    await fetch(`http://45.79.198.164:5000/season/add`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(seasonData),
    })

    //get season id newest 
    const listSeasson = await fetch(`http://45.79.198.164:5000/season?film=${req.query.slug}`)
    const getSeasonEnd = await listSeasson.json()
    const seasonId = getSeasonEnd[getSeasonEnd.length - 1].id
    //get list episode newest
    const listEpisodeAdd = dataSoundtrack.listEpisodeAdd;
    const episodeArray = []
    for (let i = 0; i < listEpisodeAdd.length; i++) {
      const temp = {
        name: listEpisodeAdd[i].name,
        slug: listEpisodeAdd[i].slug + "-" + seasonId,
        release_date: listEpisodeAdd[i].release_date,
        season_id: seasonId
      }
      episodeArray.push(temp)
    }
    //add speceial episode
    const specialEpisode = {
      name: 'Special Episode',
      slug: `special-episode-${seasonId}`,
      season_id: seasonId
    }
    episodeArray.push(specialEpisode)
    //2. add episode on season id newest
    await fetch(`http://45.79.198.164:5000/episode/addList`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(episodeArray),
    })
    const listSoundtrack = dataSoundtrack.dataSoundtrack;
    //add soundtrack
    const listEpisodeRes = dataSoundtrack.listEpisode;
    let countSpecialEpisode = listSoundtrack.length;
    for (let i = 0; i < listEpisodeRes.length; i++) {
      countSpecialEpisode = countSpecialEpisode - listEpisodeRes[i].soundtrackCount
    }
    const specialEpisodeWithCount = {
      name: 'Special Episode',
      slug: `special-episode-${seasonId}`,
      soundtrackCount: countSpecialEpisode,
      season_id: seasonId
    }
    listEpisodeRes.push(specialEpisodeWithCount)

    //get id episode
    const getListEpisode = await fetch(`http://45.79.198.164:5000/episode?film=${req.query.slug}&season=${seasonPart}`)
    const listEpisodeTemp = await getListEpisode.json();
    //add id episode to array
    const listEpisode = []
    for (let i = 0; i < listEpisodeRes.length; i++) {
      const temp = {
        ...listEpisodeRes[i],
        episode_id: listEpisodeTemp[i].id
      }
      listEpisode.push(temp)
    }
    let listSoundtrackAdd = []
    //format list sountrack 
    for (let i = 0; i < listSoundtrack.length; i++) {
      if (listSoundtrack[i].soundtrackUrl.includes("youtube")) {
        const temp = {
          name: listSoundtrack[i].soundtrackName,
          slug: listSoundtrack[i].soundtrackName?.toLowerCase().replace(/\s+/g, '-').replace("&", "and"),
          artist: listSoundtrack[i].soundtrackSingle,
          youtube_link: listSoundtrack[i].soundtrackUrl,
          film_id: req.query.film_id
        }
        listSoundtrackAdd.push(temp)
      } else if (listSoundtrack[i].soundtrackUrl.includes("spotify")) {
        const temp = {
          name: listSoundtrack[i].soundtrackName,
          slug: listSoundtrack[i].soundtrackName?.toLowerCase().replace(/\s+/g, '-').replace("&", "and"),
          artist: listSoundtrack[i].soundtrackSingle,
          spotify_link: listSoundtrack[i].soundtrackUrl,
          film_id: req.query.film_id
        }
        listSoundtrackAdd.push(temp)
      } else if (listSoundtrack[i].soundtrackUrl.includes("amazon")) {
        const temp = {
          name: listSoundtrack[i].soundtrackName,
          slug: listSoundtrack[i].soundtrackName?.toLowerCase().replace(/\s+/g, '-').replace("&", "and"),
          artist: listSoundtrack[i].soundtrackSingle,
          amazon_link: listSoundtrack[i].soundtrackUrl,
          film_id: req.query.film_id
        }
        listSoundtrackAdd.push(temp)
      } else {
        const temp = {
          name: listSoundtrack[i].soundtrackName,
          slug: listSoundtrack[i].soundtrackName?.toLowerCase().replace(/\s+/g, '-').replace("&", "and"),
          artist: listSoundtrack[i].soundtrackSingle,
          apple_link: listSoundtrack[i].soundtrackUrl,
          film_id: req.query.film_id
        }
        listSoundtrackAdd.push(temp)
      }
    }
    let listSoundtrackTemp = []
    for (let i = 0; i < listEpisode.length; i++) {
      const countSong = listEpisode[i].soundtrackCount;
      listSoundtrackTemp = listSoundtrackAdd.splice(0, countSong)

      const soundtrackArray = []
      for (let x = 0; x < listSoundtrackTemp.length; x++) {
        const temp = {
          ...listSoundtrackTemp[x],
          episode_id: listEpisode[i].episode_id
        }
        soundtrackArray.push(temp)
      }

      // add soundtrack for episode
      const postSoundtrack = await fetch(`http://45.79.198.164:5000/soundtrack/addList`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(soundtrackArray),
      });

      formatData.push(postSoundtrack)
    }
    // add soundtrack not episode
    const postSoundtrackNotEpisode = await fetch(`http://45.79.198.164:5000/soundtrack/addList`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(listSoundtrackAdd),
    });

    formatData.push(postSoundtrackNotEpisode)
  }
  return formatData;
});

app.get('/crawl-kenmei', async (req, res) => {
  console.log('url', req.query.url);
  
  let dataSoundtrack = await scrapeKenmei(req.query.url)
  console.log(dataSoundtrack);

  return;
});

app.listen(port, () => console.log(`Example app listening on port ${port}`));
